### ISSUE TITLE
Adicionar instruções de como iniciar o backend

### ISSUE THREAD

**Issue by eduhique** [joseiscj/eStore#3]
A principio não consegui iniciar o backend, mas esse trecho, consegui iniciar:
https://github.com/joseiscj/eStore/blob/0d494a6f421c06dda33be790cd36c76baa2da12b/backend/server.js#L6

para:

``` {javascript}
mongoose.connect('mongodb://localhost:27017/nodeapi', { useUnifiedTopology: true, useNewUrlParser: true });
```

Porém não consigo fazer nem POST, nem GET. Quando tento fazer POST com um body vazio, até recebo um erro de validação, mas quando coloco os dados do schema a solicitação não é concluída.

**Comment by eduhique** [comment]
Portanto, é muito interessante colocar instruções de como iniciar a aplicação adequadamente.

**Comment by joseiscj** [comment]
Olá, Eduardo. Para iniciar o back basta entrar no diretório "backend" e executar o comando "npm start". Você fez assim?

**Comment by eduhique** [comment]
Fiz sim. Mas só iniciou depois que fiz a modificação que indiquei.

**Comment by joseiscj** [comment]
Okay. Consigo fazer GET e POST tranquilamente aqui. 
Um exemplo de requisição que fiz para o POST:

Rota:
`http://localhost:3001/produtos/`

Corpo da requisição:
` {
        "nome": "Chave de ferramentas",
        "descricao": "Ótima chave de ferramentas",
        "preco": 500
    }`
