### ISSUE TITLE
Usa React functional components ao invés de Classes

### ISSUE THREAD

**Issue by vitoria** [joseiscj/eStore#4]
Usando React functional components seu código vai ficar mais enxuto e você ainda vou poder usar a maravilha dos hooks do react para controlar os estados do componente. Você pode encontrar mais informações aqui: [React Hooks](https://pt-br.reactjs.org/docs/hooks-intro.html), [React Functional Components vs Classes](https://medium.com/@Zwenza/functional-vs-class-components-in-react-231e3fbd7108#:~:text=The%20most%20obvious%20one%20difference,which%20returns%20a%20React%20element.).

**Comment by joseiscj** [comment]
Obrigado pela sugestão, Vitória!
