### ISSUE TITLE
Estrutura das pastas

### ISSUE THREAD

**Issue by camilacarvalho** [joseiscj/eStore#5]
Gostei muito do projeto, José Ivan. Como sugestão acho que seria interessante deixar routes no mesmo nível que as pastas controllers e model. Isso não influência muito no projeto, mas acho que fica mais organizado. Acho interessante a forma que [esse site](https://medium.com/@mateus1198/como-estruturo-meus-projetos-usando-express-e-nodejs-ac9a0daa5ed5) explica como faz a estruturação.

**Comment by joseiscj** [comment]
Obrigado pela sugestão, Camila!
